[package]
name = "trello-velocity-calculator"
version = "2021.5.0"
authors = ["Tim Hütz <tim+github@janke.biz>"]
edition = "2018"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["native-tls"]

[dependencies.tokio]
version = "1.5"
default-features = false
features = ["full"]

[dependencies.toml]
version = "0.5"
default-features = false